version: '3'
services:
  hub:
    image: selenium/hub:4.27
    ports:
      - 4444:4444
  chrome:
    image: selenium/node-chromium:4.27
    shm_size: '1g'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      # SE_NODE_MAX_SESSIONS=4 if using better vm machine
      - SE_NODE_MAX_SESSIONS=1
  firefox:
    image: selenium/node-firefox:4.27
    shm_size: '1g'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      # SE_NODE_MAX_SESSIONS=4 if using better vm machine
      - SE_NODE_MAX_SESSIONS=1